CREATE TABLE user_register (
register_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
email varchar(255) NOT NULL,
password  varchar(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)