CREATE TABLE category(
    category_id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    category_name varchar(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

)